name: Go CI

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.16'

      - name: Initialize Go Modules
        run: go mod init github.com/JanhviMaddeshiya/MyApp

      - name: Build
        run: go build ./...

      # - name: CD
      #   run: |
      #     cd ..
      #     cd ..
      #     ls
      #     cd MyApp
      #     cd MyApp
      #     cd go
      #     ls
        
      - name: Run Tests
        run: |
          cd ..
          cd ..
          ls
          cd MyApp
          cd MyApp
          cd go
          ls
          go test .

      - name: Install golangci-lint
        run: |
          wget -O - -q https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.1

      - name: Add golangci-lint to PATH
        run: echo "::add-path::$(go env GOPATH)/bin"

      - name: Lint with GolangCI-Lint
        run: golangci-lint run
        
      # - name: Lint with GolangCI-Lint
      #   run: golangci-lint run
